name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup_alpine
        uses: jirutka/setup-alpine@v1
        with:
          branch: edge
          extra-repositories: |
            http://dl-cdn.alpinelinux.org/alpine/edge/testing

      - name: setup_git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch main

      - name: add_packages
        run: |
          apk add alpine-sdk atool axel bash clang coreutils cmake curl gawk git libc++ linux-headers lld make openssh openssl python3 samurai wget zstd
        shell: alpine.sh --root {0}

      - name: run_build
        run: |
          sh build.sh
        shell: alpine.sh {0}

      - name: create_release_tag
        id: create_release
        uses: rearrangement/auto-releases@v1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "19.1.7"
          prerelease: false
          title: 19.1.7

      - name: upload_packages
        id: upload_release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 19.1.7.tar.zst
          tag: 19.1.7
          overwrite: true
          file_glob: true
